# example netlify.toml
[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[dev]
  command = "hugo server -w"

[build.environment]
  HUGO_VERSION = "0.139.0"

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false

[[plugins]]
  package = "@netlify/plugin-nextjs"